language: r

sudo: required

env:
  global:
    - WARNINGS_ARE_ERRORS=1
  matrix:
    - NOT_CRAN="true"
    - NOT_CRAN="false"

r_binary_packages: 
  - testthat
  - party
  - pROC
  - e1071
  - mvtnorm
  - ggplot2
  - rpart
  - modeltools
  - proxy
  - doParallel
  - MASS
  - knitr

r_github_packages:
  - zachmayer/caretEnsemble
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change